name: dio_flutter_transformer2
description:  A dio transformer espically for flutter, by which the json decoding will be in background with [compute] function in flutter sdk.

version: 4.1.0
homepage: https://github.com/arklabsnz/dio_flutter_transformer

environment:
  sdk: ">2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
